# Etapa 1: Construcción
FROM node:18 AS build

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos de configuración y dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia todo el código de la aplicación al contenedor
COPY . .

# Compila la aplicación Angular en modo de producción
RUN npm install -g @angular/cli@16.0.0 && ng build --configuration production

# Etapa 2: Servidor de Producción
FROM node:18

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos compilados de Angular al contenedor
COPY --from=build /app/dist/votaciones /app

# Instala http-server
RUN npm install -g http-server

# Exponer el puerto que se va a usar
EXPOSE $PORT

# Comando para ejecutar http-server, usando el puerto definido por Heroku o 8080 como predeterminado
CMD ["sh", "-c", "http-server -p ${PORT:-8080} -a 0.0.0.0"]
