# Etapa de construcción
FROM node:18 AS build

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de configuración y dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia todo el código de la aplicación al contenedor
COPY . .

# Compila la aplicación Angular en modo de producción
RUN npm run build -- --configuration production

# Etapa 2: Servidor NGINX
FROM nginx:alpine

# Copia los archivos compilados de Angular al contenedor de NGINX
COPY --from=build /app/dist/votaciones /usr/share/nginx/html

# Copia la configuración personalizada de NGINX
COPY nginx.conf /etc/nginx/conf.d/default.conf
