# Etapa de construcción
FROM node:18 AS build

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de configuración y dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia todo el código de la aplicación al contenedor
COPY . .

# Compila la aplicación Angular en modo de producción
RUN npm run build -- --configuration production

# Etapa de producción (opcional)
FROM node:18 AS production

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos compilados desde la etapa de construcción
COPY --from=build /app/dist/votaciones /app

# Instala un servidor estático para servir los archivos
RUN npm install -g serve

# Comando para servir la aplicación
CMD ["serve", "-s", "app", "-l", "3000"]

# Exponer el puerto 3000
EXPOSE 3000
